auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Yang Yiyuan's blog”
title: Yang Yiyuan's blog
description: colorful life of Yiyuan.
url: http://yyysjz1997.github.io
feed: /atom.xml
author_info: <a href="http://yyysjz1997.github.io/">yyysjz1997</a>
